name: Deploy Loaded Checklist to Azure

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore LoadedChecklist/backend/LoadedChecklist.csproj

      - name: Build the app
        run: dotnet build LoadedChecklist/backend/LoadedChecklist.csproj --configuration Release

      - name: Publish the app
        run: dotnet publish LoadedChecklist/backend/LoadedChecklist.csproj -c Release -o release

      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: loaded-checklist
          package: release
