name: Deploy Loaded Checklist to Azure

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Setup Node.js for Vite
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        working-directory: LoadedChecklist/frontend
        run: npm ci

      - name: Build frontend
        working-directory: LoadedChecklist/frontend
        run: npm run build

      - name: List frontend build output
        run: ls -la LoadedChecklist/frontend/dist || echo "dist folder missing"

      - name: Copy frontend to backend wwwroot
        run: |
          rm -rf LoadedChecklist/backend/wwwroot
          mkdir -p LoadedChecklist/backend/wwwroot
          cp -r LoadedChecklist/frontend/dist/* LoadedChecklist/backend/wwwroot/

      - name: Restore backend dependencies
        working-directory: LoadedChecklist/backend
        run: dotnet restore LoadedChecklist.csproj

      - name: Build backend
        working-directory: LoadedChecklist/backend
        run: dotnet build LoadedChecklist.csproj --configuration Release

      - name: Publish backend
        working-directory: LoadedChecklist/backend
        run: dotnet publish LoadedChecklist.csproj -c Release -o ../../release

      - name: Azure Login via OIDC
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: loaded-checklist
          package: release
